#!/bin/bash

#written by swapnull
#This gets the current battery and echos its icon out of the file. If the battery is charging and not fully charged then show increasing icons

source ~/.config/panel/panel_globals
battery=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)
icon=${BATTERY_FULL_ICON}

if [[ "$battery" -gt 95 && "$battery_status" = "Charging" ]]; then
	battery=100
fi

if [ "$battery_status" = "Charging" ]; then
	#use this to show a lightning bolt when charging
	icon=${BATTERY_CHARGING_ICON}

	#use this if you would prefer a changing battery icon that goes up
#		curr=$(cat ~/.bin/currentbatteryicon)
#		
#		if [ "$curr" = ${BATTERY_EMPTY_ICON} ]; then	
#			icon=${BATTERY_QUATER_ICON}
#		fi
#		
#		if [ "$curr" = ${BATTERY_QUATER_ICON} ]; then
#			icon=${BATTERY_HALF_ICON}
#		
#		fi
#		if [ "$curr" = ${BATTERY_HALF_ICON} ]; then
#			icon=${BATTERY_THREEQUATER_ICON}
#		fi
#		if [ "$curr" = ${BATTERY_THREEQUATER_ICON} ]; then
#			icon=${BATTERY_FULL_ICON}
#		fi
#		if [ "$curr" = ${BATTERY_FULL_ICON} ]; then
#		
#			icon=${BATTERY_EMPTY_ICON}
#		fi
#
#		echo $icon > ~/.bin/currentbatteryicon


fi
if [ "$battery_status" = "Discharging" ]; then
	#Get the appropriate symbol
	if [ "$battery" -lt 100 ]; then
		icon=${BATTERY_FULL_ICON}
	fi 

	if [ "$battery" -lt 80 ]; then
		icon=${BATTERY_THREEQUATER_ICON}
	fi

	if [ "$battery" -lt 55 ]; then
		icon=${BATTERY_HALF_ICON}
	fi

	if [ "$battery" -lt 35 ]; then
		icon=${BATTERY_QUATER_ICON}
	fi

	if [ "$battery" -lt 15 ]; then
		icon=${BATTERY_EMPTY_ICON}
	fi
fi


echo $icon $battery
