#! /bin/bash

source ~/.config/panel/panel_globals

xrandr --output eDP1 --mode 1920x1200
xset +fp $HOME/.fonts
xset fp rehash
xrdb -merge ~/.Xresources

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d ${TERMINAL_ICON} ${CODE_ICON} ${CHROME_ICON} ${SPOTIFY_ICON} 5 6

bspc rule -a firefox desktop=^3
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale ~/Downloads/mountains.jpg

sxhkd &
panel &
